version: '3'

services:
    zoo1:
        image: zookeeper:3.5
        container_name: zoo1
        hostname: zoo1
        ports: 
            - '2181:2181'
        environment: 
            ZOO_MY_ID: '1'
        volumes: 
            - ./zoo.cfg:/conf/zoo.cfg
        networks: 
            zoo-net:
                ipv4_address: 192.168.100.2
    zoo2:
        image: zookeeper:3.5
        container_name: zoo2
        hostname: zoo2
        ports: 
            - '2182:2181'
        environment: 
            ZOO_MY_ID: '2'
        volumes: 
            - ./zoo.cfg:/conf/zoo.cfg
        networks: 
            zoo-net:
                ipv4_address: 192.168.100.3
    zoo3:
        image: zookeeper:3.5
        container_name: zoo3
        hostname: zoo3
        ports: 
            - '2183:2181'
        environment: 
            ZOO_MY_ID: '3'
        volumes: 
            - ./zoo.cfg:/conf/zoo.cfg
        networks: 
            zoo-net:
                ipv4_address: 192.168.100.4
        
networks: 
    zoo-net:
        ipam: 
            driver: default
            config: 
                - subnet: 192.168.100.0/29