version: "3"

services:
    namenode:
      image: kerios/hdfs-namenode:2.9.2
      container_name: namenode
      restart: always
      ports:
        - 9870:9870
        - 9000:9000
      environment:
        - CLUSTER_NAME=test
    datanode:
      image: hdfs-datanode:2.9.2
      container_name: datanode
      restart: always
      environment:
        SERVICE_PRECONDITION: "namenode:9000"